### ISSUE TITLE
Eager loading on import.meta.glob() causing app to break

### ISSUE THREAD

**Issue by harryqt** [onix-systems-php/hyperf-inertia#17]
Vite enables code splitting by default when using their `import.meta.glob()` function. But I could not disable it despite having `{ eager: true }`. Turns out there was typo. Closing bracket after `*.svelte'` should be at end.

https://github.com/onix-systems-php/hyperf-inertia/blob/829e0f8adf2ec0135af6cdfc967e14d2230b2473/src/Commands/Stubs/Svelte/app.js#L11

It should be:

```js
resolve: (name) => resolvePageComponent(`./Pages/${name}.svelte`, import.meta.glob('./Pages/**/*.svelte', { eager: true })),
```

However if I do that app builds successfully, but shows "Internal Server Error" upon browsing and errors in console:

```sh
[ERROR] Unable to locate file in Vite manifest: storage/inertia/js/Pages/Test.svelte. (View: /Users/harry/hyperf1-test/storage/view/layouts/inertia.blade.php)[73] in /Users/harry/hyperf1-test/vendor/hyperf/view/src/Render.php
[ERROR] #0 /Users/harry/hyperf1-test/vendor/hyperf/view/src/Render.php(52): Hyperf\View\Render->getContents('layouts/inertia', Array)
#1 /Users/harry/hyperf1-test/vendor/onix-systems-php/hyperf-inertia/src/InertiaResponse.php(102): Hyperf\View\Render->render('layouts/inertia', Array)
#2 /Users/harry/hyperf1-test/config/routes.php(13): OnixSystemsPHP\HyperfInertia\InertiaResponse->toResponse(Object(Hyperf\HttpServer\Request))
#3 /Users/harry/hyperf1-test/vendor/hyperf/http-server/src/CoreMiddleware.php(139): Hyperf\HttpServer\Router\DispatcherFactory->{closure}(Object(Hyperf\HttpServer\Request))
#4 /Users/harry/hyperf1-test/vendor/hyperf/http-server/src/CoreMiddleware.php(97): Hyperf\HttpServer\CoreMiddleware->handleFound(Object(Hyperf\HttpServer\Router\Dispatched), Object(Hyperf\HttpMessage\Server\Request))
```

`manifest.json` when `{ eager: true }` is set:

```js
{
  "storage/inertia/css/app.css": {
    "file": "assets/app-l0sNRNKZ.js",
    "name": "app",
    "src": "storage/inertia/css/app.css",
    "isEntry": true
  },
  "storage/inertia/js/app.js": {
    "file": "assets/app-8Jj4kO3r.js",
    "name": "app",
    "src": "storage/inertia/js/app.js",
    "isEntry": true
  }
}
```

when `{ eager: true }` is omitted:
```js
{
  "storage/inertia/css/app.css": {
    "file": "assets/app-l0sNRNKZ.js",
    "name": "app",
    "src": "storage/inertia/css/app.css",
    "isEntry": true
  },
  "storage/inertia/js/Pages/Test.svelte": {
    "file": "assets/Test-XgqcBhVH.js",
    "name": "Test",
    "src": "storage/inertia/js/Pages/Test.svelte",
    "isDynamicEntry": true,
    "imports": [
      "storage/inertia/js/app.js"
    ]
  },
  "storage/inertia/js/app.js": {
    "file": "assets/app-CuT2_zd_.js",
    "name": "app",
    "src": "storage/inertia/js/app.js",
    "isEntry": true,
    "dynamicImports": [
      "storage/inertia/js/Pages/Test.svelte"
    ]
  }
}
```

**Comment by harryqt** [comment]
I just wanted to let you and others know that there’s a new project, [laravel-spawn](https://github.com/YanGusik/laravel-spawn), based on [true-async](https://github.com/true-async).
